import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import GameNavbar from "@/components/ui/gameNavbar";
import { ClerkProvider } from "@clerk/nextjs";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "BloomPoint",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${spaceGrotesk.variable} font-sans antialiased text-white relative`}
      >
        {/* Visual Effect - positioned relative to body */}
        <img
          className="fixed top-0 left-0 w-full h-full object-cover opacity-80 -z-10"
          src="/gradient.png"
          alt="Gradient-img"
        />
        <div className="h-0 w-[40rem] fixed top-[20%] right-[-5%] shadow-[0_0_900px_20px_#F87171] -rotate-[30deg] -z-10"></div>

        <ClerkProvider>
          <GameNavbar />

          {/* Main content area */}
          <div className="min-h-screen">{children}</div>
        </ClerkProvider>
      </body>
    </html>
  );
}
